<tsa:hidden name="formtype" value="RFQ"/>
<tsa:hidden name="RfqHeader_rfqNumber" value="<%=rfqHeader.getRfqNumber()%>"/>
<tsa:hidden name="RfqHeader_rfqAmendment" value="<%=s_rfqAmendment%>"/>
<tsa:hidden name="RfqHeader_fiscalYear" value="<%=s_fiscalYear%>"/>
<tsa:hidden name="RfqHeader_rfqType" value="${RfqHeader_rfqType}"/>
<tsa:hidden name="RfqHeader_status" value="<%=s_rfqStatus%>"/>
<tsa:hidden name="RfqHeader_icRfqHeader" value="<%=bd_icRfqHeader%>"/>
<tsa:hidden name="RfqHeader_icHeaderHistory" value="<%=rfqHeader.getIcHeaderHistory()%>"/>
<tsa:hidden name="RfqHeader_vendorAwarded" value="<%=rfqHeader.getVendorAwarded()%>"/>
<tsa:hidden name="RfqLine_icRfqHeader" value="<%=bd_icRfqHeader%>"/>
<tsa:hidden name="RfqBid_icRfqHeader" value="<%=bd_icRfqHeader%>"/>
<tsa:hidden name="RfqQuestion_icRfqHeader" value="<%=bd_icRfqHeader%>"/>
<tsa:hidden name="RfqVendor_icRfqHeader" value="<%=bd_icRfqHeader%>"/>
<tsa:hidden name="RfqVendor_vendorId" value=""/>
<tsa:hidden name="VendorDocument_icRfqHeader" value="<%=bd_icRfqHeader%>"/>
<tsa:hidden name="VendorDocument_vendorId" value=""/>
<tsa:hidden name="DocAttachment_icHeader" value="<%=bd_icRfqHeader%>"/>
<tsa:hidden name="DocComment_icHeader" value="<%=bd_icRfqHeader%>"/>
<tsa:hidden name="DocComment_icLine" value="0"/>
<tsa:hidden name="VendorQuestion_icRfqHeader" value="<%=bd_icRfqHeader%>"/>
<tsa:hidden name="lineCount" value="<%=i_lineCount%>"/>
<tsa:hidden name="rfqaction" value=""/>
<tsa:hidden name="currentPage" value="<%=s_current_page%>"/>
<tsa:hidden name="printtype" value="Rfq"/>
<tsa:hidden name="frompage" value="review"/>