<tsa:hidden name="formtype" value="PO"/>
<tsa:hidden name="PoHeader_icPoHeader" value="<%=bd_ic_po_header%>"/>
<tsa:hidden name="PoLine_icPoHeader" value="<%=bd_ic_po_header%>"/>
<tsa:hidden name="PoHeader_poNumber" value="<%=poHeader.getPoNumber()%>"/>
<tsa:hidden name="PoSecurity_poNumber" value="<%=poHeader.getPoNumber()%>"/>
<tsa:hidden name="PoHeader_releaseNumber" value="<%=bd_release_number%>"/>
<tsa:hidden name="PoHeader_revisionNumber" value="<%=bd_revision_number%>"/>
<tsa:hidden name="PoHeader_status" value="<%=s_po_status%>"/>
<tsa:hidden name="PoHeader_poType" value="<%=s_po_type%>"/>
<tsa:hidden name="PoHeader_vendorId" value="<%=poHeader.getVendorId()%>"/>
<tsa:hidden name="PoHeader_vendorName" value="<%=poHeader.getVendorName()%>"/>
<tsa:hidden name="PoHeader_vendContactCode" value="<%=poHeader.getVendContactCode()%>"/>
<tsa:hidden name="PoHeader_itemLocation" value="<%=poHeader.getItemLocation()%>"/>
<tsa:hidden name="PoHeader_buyerCode" value="<%=poHeader.getBuyerCode()%>"/>
<tsa:hidden name="PoHeader_icHeaderHistory" value="<%=poHeader.getIcHeaderHistory()%>"/>
<tsa:hidden name="PoHeader_icHeaderKey" value="<%=poHeader.getIcHeaderKey()%>"/>
<tsa:hidden name="PoHeader_fiscalYear" value="<%=poHeader.getFiscalYear()%>"/>
<tsa:hidden name="Account_icHeader" value="<%=bd_ic_po_header%>"/>
<tsa:hidden name="Account_icLine" value="0"/>
<tsa:hidden name="Account_accountType" value="POH"/>
<tsa:hidden name="DocAttachment_icHeader" value="<%=bd_ic_po_header%>"/>
<tsa:hidden name="DocComment_icHeader" value="<%=bd_ic_po_header%>"/>
<tsa:hidden name="DocComment_icLine" value="0"/>
<tsa:hidden name="lineCount" value="<%=i_line_count%>"/>
<tsa:hidden name="poForwardOption" value=""/>
<tsa:hidden name="goforward" value=""/>
<tsa:hidden name="poaction" value=""/>
<tsa:hidden name="PoHeader_displayNumber" value="<%=poHeader.getDisplayPoNumber()%>"/>
<tsa:hidden name="currentPage" value="<%=s_current_page%>"/>
<tsa:hidden name="Schedule_icHeader" value="<%=bd_ic_po_header%>"/>
<tsa:hidden name="Schedule_documentType" value="POH"/>
<tsa:hidden name="budgetAction" value=""/>
<tsa:hidden name="budgetMake"  value=""/>
<tsa:hidden name="budgetType" value=""/>
<tsa:hidden name="budgetYear" value=""/>
<tsa:hidden name="VendorInsurance_icPoHeader" value="<%=bd_ic_po_header%>"/>
<tsa:hidden name="VendorInsurance_contNumber" value="<%=s_po_number%>"/>
<tsa:hidden name="VendorInsurance_vendorId" value="<%=poHeader.getVendorId()%>"/>
<tsa:hidden name="PoHeader_udf10Code" value="<%=poHeader.getUdf10Code()%>"/>
