<tsa:hidden name="SaleHeader_icSaleHeader" value="<%=s_icSaleHeader%>"/>
<tsa:hidden name="SaleHeader_saleNumber" value="<%=s_saleNumber%>"/>
<tsa:hidden name="SaleHeader_amendment" value="<%=s_amendment%>"/>
<tsa:hidden name="SaleHeader_status" value="<%=s_status%>"/>
<tsa:hidden name="SaleHeader_fiscalYear" value="<%=s_fiscalYear%>"/>
<tsa:hidden name="SaleLine_icSaleHeader" value="<%=s_icSaleHeader%>"/>
<tsa:hidden name="SaleBid_icSaleHeader" value="<%=s_icSaleHeader%>"/>
<tsa:hidden name="SaleBuyer_icSaleHeader" value="<%=s_icSaleHeader%>"/>
<tsa:hidden name="SaleBuyer_buyerCode" value=""/>
<tsa:hidden name="BuyerDocument_icSaleHeader" value="<%=s_icSaleHeader%>"/>
<tsa:hidden name="BuyerDocument_buyerCode" value=""/>
<tsa:hidden name="DocAttachment_icHeader" value="<%=s_icSaleHeader%>"/>
<tsa:hidden name="DocComment_icHeader" value="<%=s_icSaleHeader%>"/>
<tsa:hidden name="DocComment_icLine" value="0"/>
<tsa:hidden name="Default_referenceType" value="SLH"/>
<tsa:hidden name="deleteall" value=""/>
<tsa:hidden name="allowBrowse" value="true"/>
<tsa:hidden name="formNumber" value="<%=s_saleNumber%>"/>
<tsa:hidden name="formStatus" value="<%=s_status%>"/>
<tsa:hidden name="formType" value="SALE"/>
<tsa:hidden name="fiscalYear" value="<%=s_fiscalYear%>"/>
<tsa:hidden name="currentPage" value="<%=s_current_page%>"/>